# Generated by Django 2.1 on 2018-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='denuncia',
            fields=[
                ('idDenuncia', models.AutoField(primary_key=True, serialize=False)),
                ('idTipoDenuncia', models.IntegerField()),
                ('asuntoDenuncia', models.CharField(max_length=100)),
                ('descripcionDenuncia', models.CharField(max_length=300)),
                ('evidenciaDenuncia', models.FileField(upload_to='')),
                ('ubicacionDeuncia', models.CharField(max_length=100)),
                ('idEstadoDenuncia', models.IntegerField()),
            ],
        ),
    ]
