# Generated by Django 2.1 on 2018-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homeApp',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('idLeccion', models.IntegerField()),
                ('idDenuncia', models.IntegerField()),
            ],
        ),
    ]
