# Generated by Django 2.1 on 2018-09-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('apellidoUsuario', models.CharField(max_length=100)),
                ('direccionUsuario', models.CharField(max_length=100)),
                ('telefonoUsuario', models.IntegerField()),
                ('emailUsuario', models.CharField(max_length=100)),
            ],
        ),
    ]
