# Generated by Django 2.1 on 2018-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leccion',
            fields=[
                ('idLeccion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreLeccion', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=800)),
                ('imagen', models.FileField(upload_to='')),
            ],
        ),
    ]
